version: '3.8'

services:
  # Web application
  web:
    build: .
    container_name: sdu_event_hub
    restart: always
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_change_in_production}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-none}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:-SDUEventHubBot}
      - BASE_URL=${BASE_URL:-http://localhost:5004}
      # Uncomment for PostgreSQL - comment out for SQLite
      # - DATABASE_URL=postgresql://postgres:postgres@db:5432/sdu_event_hub
    volumes:
      - app_data:/app/instance
      - app_static:/app/app/static
    ports:
      - "5004:5000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
  
  # Database (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: sdu_event_hub_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sdu_event_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  app_data:
    # Persistent storage for SQLite database and application data
  app_static:
    # Persistent storage for uploaded files and static assets
  postgres_data:
    # Persistent storage for PostgreSQL database